<a href="https://colab.research.google.com/github/beakdongH/Colaboratory/blob/main/AImath02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=[1,2,3,4]
b=[[1,2,3,4],
   [1,2,2,1]]

A = np.matrix([[1,2],
               [0,1]])
B = np.matrix([[1,2],
               [3,4]])
C = np.matrix([[3,2],
               [-4,5]])
D = np.matrix([[2],
               [1]])
I = np.matrix([[1,0],
               [0,1]])

print(A)
print(A*I)
print(I*D)

[[1 2]
 [0 1]]


ValueError: ignored

In [ ]:
import numpy as np

a=[1,2,3,4]
b=[[1,2,3,4],
   [1,2,2,1]]

R = np.matrix([[243,243,243],
               [243,183,243],
               [243,243,243]])
G = np.matrix([[98,98,98],
               [98,117,98],
               [98,98,98]])
B = np.matrix([[166,166,166],
               [166,255,166],
               [166,166,166]])

print(1/3*(R+G+B))

[[169. 169. 169.]
 [169. 185. 169.]
 [169. 169. 169.]]


In [ ]:
import numpy as np

a=[1,2,3,4]
b=[[1,2,3,4],
   [1,2,2,1]]

T = np.matrix([[0,1,0],
               [0,0,1],
               [0,0,0]])
A = np.matrix([[0,0,0],
               [0,255,0],
               [0,0,0]])

print(A*T)
print(T*A)

[[  0   0   0]
 [  0   0 255]
 [  0   0   0]]
[[  0 255   0]
 [  0   0   0]
 [  0   0   0]]


In [ ]:
import numpy as np

T = np.matrix([[0,1,0],
               [0,0,1],
               [0,0,0]])
A = np.matrix([[0,0,0],
               [0,255,0],
               [0,0,0]])

print(A*T)
print(T*A)

In [ ]:
import numpy as np

T = np.matrix([[0,0,1],
               [0,1,0],
               [1,0,0]])
A = np.matrix([[0,0,0],
               [255,0,0],
               [255,0,0]])

print(A*T)
print(T*A)